services:
  db:
    image: postgres:16-alpine
    container_name: comanda_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: comanda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d comanda']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
